### ISSUE TITLE
Exception:/user/register/v2 exception:Expected URL scheme 'http' or 'https' but no colon was found

### ISSUE THREAD

**Issue by YuTongHon** [maxim-top/maxim-android#3]
客户报错： 2020-06-10 10:22:14.427 23074-30122/com.example.myapplication E/BMXHttpClient: sendRequest Exception:/user/register/v2 exception:Expected URL scheme 'http' or 'https' but no colon was found

**Comment by h001erolee** [comment]
已解决。原因是通过dns获取服务器地址是出错。
