### ISSUE TITLE
调用BMXUserManager.signInByName()或者signUpNewUser都会异常奔溃

### ISSUE THREAD

**Issue by Wanghehuang** [maxim-top/maxim-android#5]
08-18 13:47:07.926 32071-32158/com.evideostb.maxim.proxy W/art: Native thread exiting without having called DetachCurrentThread (maybe it's going to use a pthread_key_create destructor?): Thread[24,tid=32158,Native,Thread*=0xb7828d88,peer=0x130040a0,"Thread-399"]
08-18 13:47:07.926 32071-32158/com.evideostb.maxim.proxy A/art: art/runtime/thread.cc:1057] Native thread exited without calling DetachCurrentThread: Thread[24,tid=32158,Native,Thread*=0xb7828d88,peer=0x130040a0,"Thread-399"]
    
    --------- beginning of crash
08-18 13:47:07.945 32071-32158/com.evideostb.maxim.proxy A/libc: Fatal signal 11 (SIGSEGV), code 1, fault addr 0xc8 in tid 32158 (Thread-399)
08-18 13:47:07.978 32071-32151/com.evideostb.maxim.proxy I/BMXHttpClient: sendRequest response:{"code":402,"message":"Operation rejected"}
08-18 13:47:07.979 32071-32151/com.evideostb.maxim.proxy W/floo_log: <2020/08/18 13:47:07:979> <W> fetchTokenByName() retCode : 0
08-18 13:47:07.979 32071-32151/com.evideostb.maxim.proxy D/floo_log: <2020/08/18 13:47:07:979> <D> fetchTokenByName() response : {"code":402,"message":"Operation rejected"}
08-18 13:47:07.979 32071-32151/com.evideostb.maxim.proxy E/floo_log: <2020/08/18 13:47:07:979> <E> fetchTokenByName() response : {"code":402,"message":"Operation rejected"}
08-18 13:47:08.004 1051-1499/? D/qiangvvv: [Thread-121(121): MicroServiceActivity.java:636] - sleep...
08-18 13:47:08.047 25280-25280/? I/DEBUG: *** *** *** *** *** *** *** *** *** *** *** *** *** *** *** ***
08-18 13:47:08.047 25280-25280/? I/DEBUG: Build fingerprint: 'Android/rk3288/rk3288:5.1.1/LMY49F/264:eng/dev-keys'
08-18 13:47:08.047 25280-25280/? I/DEBUG: Revision: '0'
08-18 13:47:08.047 25280-25280/? I/DEBUG: ABI: 'arm'
08-18 13:47:08.047 25280-25280/? I/DEBUG: pid: 32071, tid: 32158, name: Thread-399  >>> com.evideostb.maxim.proxy <<<
08-18 13:47:08.047 25280-25280/? I/DEBUG: signal 11 (SIGSEGV), code 1 (SEGV_MAPERR), fault addr 0xc8
08-18 13:47:08.067 25280-25280/? I/DEBUG: Abort message: 'art/runtime/thread.cc:1057] Native thread exited without calling DetachCurrentThread: Thread[24,tid=32158,Native,Thread*=0xb7828d88,peer=0x130040a0,"Thread-399"]'
08-18 13:47:08.067 25280-25280/? I/DEBUG:     r0 00000000  r1 9f03edd0  r2 fffffa94  r3 00000007
08-18 13:47:08.067 25280-25280/? I/DEBUG:     r4 6ffb0470  r5 3abf7e24  r6 b51ae008  r7 fffffa98
08-18 13:47:08.067 25280-25280/? I/DEBUG:     r8 b782df38  r9 00000000  sl 00000013  fp 6ffb0484
08-18 13:47:08.067 25280-25280/? I/DEBUG:     ip b51aba78  sp 9f03e7e8  lr b5109ffd  pc b5109ee6  cpsr 80070030
08-18 13:47:08.067 25280-25280/? I/DEBUG: backtrace:
08-18 13:47:08.067 25280-25280/? I/DEBUG:     #00 pc 00265ee6  /system/lib/libart.so (art::verifier::MethodVerifier::FindLocksAtDexPc(art::mirror::ArtMethod*, unsigned int, std::__1::vector<unsigned int, std::__1::allocator<unsigned int> >*)+53)
08-18 13:47:08.067 25280-25280/? I/DEBUG:     # 01 pc 001f754b  /system/lib/libart.so (art::Monitor::VisitLocks(art::StackVisitor*, void (*)(art::mirror::Object*, void*), void*, bool)+250)
08-18 13:47:08.067 25280-25280/? I/DEBUG:     # 02 pc 002368d7  /system/lib/libart.so (art::StackDumpVisitor::VisitFrame()+374)
08-18 13:47:08.067 25280-25280/? I/DEBUG:     # 03 pc 00231481  /system/lib/libart.so (art::StackVisitor::WalkStack(bool)+276)
08-18 13:47:08.067 25280-25280/? I/DEBUG:     # 04 pc 002377e7  /system/lib/libart.so (art::Thread::DumpJavaStack(std::__1::basic_ostream<char, std::__1::char_traits<char> >&) const+182)
08-18 13:47:08.067 25280-25280/? I/DEBUG:     # 05 pc 00238ee7  /system/lib/libart.so (art::Thread::Dump(std::__1::basic_ostream<char, std::__1::char_traits<char> >&) const+166)
08-18 13:47:08.068 25280-25280/? I/DEBUG:     # 06 pc 00242bbd  /system/lib/libart.so (art::ThreadList::DumpLocked(std::__1::basic_ostream<char, std::__1::char_traits<char> >&)+120)
08-18 13:47:08.068 25280-25280/? I/DEBUG:     # 07 pc 00228495  /system/lib/libart.so (art::AbortState::Dump(std::__1::basic_ostream<char, std::__1::char_traits<char> >&)+272)
08-18 13:47:08.068 25280-25280/? I/DEBUG:     # 08 pc 002286df  /system/lib/libart.so (art::Runtime::Abort()+82)
08-18 13:47:08.068 25280-25280/? I/DEBUG:     # 09 pc 000a6a35  /system/lib/libart.so (art::LogMessage::~LogMessage()+1360)
08-18 13:47:08.068 25280-25280/? I/DEBUG:     # 10 pc 002366b7  /system/lib/libart.so (art::Thread::ThreadExitCallback(void*)+186)
08-18 13:47:08.068 25280-25280/? I/DEBUG:     # 11 pc 00016c0d  /system/lib/libc.so (pthread_key_clean_all()+80)
08-18 13:47:08.068 25280-25280/? I/DEBUG:     # 12 pc 0001688b  /system/lib/libc.so (pthread_exit+30)
08-18 13:47:08.068 25280-25280/? I/DEBUG:     # 13 pc 0001659d  /system/lib/libc.so (__pthread_start(void*)+32)
08-18 13:47:08.068 25280-25280/? I/DEBUG:     # 14 pc 000144c3  /system/lib/libc.so (__start_thread+6)

**Comment by theorix** [comment]
{"code":402,"message":"Operation rejected"} 这个错是因为密码不对

**Comment by theorix** [comment]
Android版本为5.1.1的机顶盒

**Comment by h001erolee** [comment]
已解决。http请求放到了native线程中。
