### ISSUE TITLE
双方聊天，在聊天界面接收消息时报SIGSEGV(SEGV_MAPERR)错误

### ISSUE THREAD

**Issue by Tomcruseztz** [maxim-top/maxim-android#6]
SDK：2.4.3    bmxchatlistener的实例有没有被提前释放
#00 pc 001d3988 /data/app/com.xieshou.healthyDerDoctor-R2-IA_tYxDvOrVlEhBV4nA==/lib/arm/libfloo.so [armeabi-v7a]
--
2 #01 pc 00218a39 /data/app/com.xieshou.healthyDerDoctor-R2-IA_tYxDvOrVlEhBV4nA==/lib/arm/libfloo.so (floo::TaskThread::threadFunc()+108) [armeabi-v7a]
3 #02 pc 00219bcb /data/app/com.xieshou.healthyDerDoctor-R2-IA_tYxDvOrVlEhBV4nA==/lib/arm/libfloo.so [armeabi-v7a]
4 #03 pc 0041971f /data/app/com.xieshou.healthyDerDoctor-R2-IA_tYxDvOrVlEhBV4nA==/lib/arm/libfloo.so [armeabi-v7a]
5 #04 pc 00073611 /system/lib/libc.so (__pthread_start(void*)+22) [armeabi-v8]
6 #05 pc 0001e47d /system/lib/libc.so (__start_thread+24) [armeabi-v8]
7 java:

**Comment by h001erolee** [comment]
已解决。http请求放到了native线程中。
