### ISSUE TITLE
发送、下载图片和语音失败

### ISSUE THREAD

**Issue by longmh** [maxim-top/maxim-android#7]
发送、下载图片和语音失败的情况，提示ServerUnknowError，版本是floo-android_2.4.2.20200527，发送消息会报错Send message: 160039897929386225 reconnect failed, result is 63

**Comment by ericliang** [comment]
你好，请问有完整日志吗？

**Comment by h001erolee** [comment]
看错误信息应该是网络故障重连几次后仍未成功。

**Comment by ericliang** [comment]
> 看错误信息应该是网络故障重连几次后仍未成功。

估计是网络问题。

已经超过30天未提供反馈，先关闭了。
